### ISSUE TITLE
Will you support gpt-3.5-turbo？

### ISSUE THREAD

**Issue by Simonmxy** [matrixgpt/matrix-chatgpt-bot#120]
When I use gpt-3.5-turbo: 
"message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",

**Comment by Simonmxy** [comment]
Thank you

> Simply open the directory - enter `npm update` and then start the chatbot and you will be able to use the new model.

**Comment by philidinator** [comment]
I tried "docker-compose down && docker-compose pull && docker-compose up -d" with Docker but received the same error message. I also cloned the latest git repository and tried to build with Docker, but unfortunately it didn't work.

**Comment by kitzler-walli** [comment]
The commands you mentioned wont update the npm dependencies - you have to update the npm packages until the next release and then you'll be able to use the new model.

**Comment by philidinator** [comment]
Okay, I deleted all Docker images. Then I cloned again, performed 'npm update' (which also ran successfully), and then ran 'docker build' again, but unfortunately encountered the same error.

**Comment by ich777** [comment]
No issue over here, just open up a container terminal and issue: `npm update` after that I had to run `npm install -g npm@9.6.0` and finally I restarted the container.
Keep in mind if you update the container image or something similar the changes will be wiped and you have to do everything again but I think when the maintainer updates the container everything will be in a working state and you don't have to issue the commands manually.

**Comment by philidinator** [comment]
Ah, it's working! Updating npm in the container. Thank you all!
