### ISSUE TITLE
bingchat-api

### ISSUE THREAD

**Issue by ich777** [matrixgpt/matrix-chatgpt-bot#121]
Hi,
is this something that can be implemented/added: https://github.com/tuhinpal/bingchat-api

Cheers

**Comment by max298** [comment]
The [waylaidwanderer api](https://github.com/waylaidwanderer/node-chatgpt-api) also supports bing, I did try this a few days back when the official API wasn't there jet. I've had some trouble getting the bot to remember the conversation context, as this is working quite differently than the ChatGPT API. I even found the api from waylaidwanderer to be quite buggy.

As this is also again an unofficial API, I am not considering supporting bing right now. However, I don't know how the maintainers feel about this.

**Comment by ich777** [comment]
Thank you for the feedback @max298!

This was just a question and I'm fine if that doesn't make it into this application since as you've said this is a completely different API and is working maybe completely different.

**Comment by ich777** [comment]
I'm closing this because I don't want to create any unnecessary noise here in the issue tracker.
