### ISSUE TITLE
Responses in threads don't work

### ISSUE THREAD

**Issue by kitzler-walli** [matrixgpt/matrix-chatgpt-bot#133]
When I set MATRIX_THREADS=true and CHATGPT_CONTEXT=thread I get the response from the bot in a thread, but when I reply within the thread the bot never recognises the answer and therefore never triggers a response from ChatGPT.
Is that a problem with my locally hosted matrix instance or with the chatbot?

**Comment by ReggieMarr** [comment]
Is this on element web ? Its working for me in element mobile but not web. I'm using dendrite though.

**Comment by Dual-0** [comment]
It is working on my synapse instance. I use element web/android.

**Comment by Jasonthefirst** [comment]
For me it is neither working on element android nor on element web. Nothing happens if I respond to the thread.

**Comment by Jasonthefirst** [comment]
I couldn't find a solution to the problem but it works with a prefix. So I chose a really short prefix and then it will also answer in threads. Apparently it won't react to messages in Threads without a prefix trigger.

**Comment by kitzler-walli** [comment]
There were a few months now that this worked just fine without trigger in threads but the latest version once again has this issue. I can chat with the bot, the answer is delivered in thread but every reply within the thread is ignored.

**Comment by kitzler-walli** [comment]
Latest release version 3.1.4

MATRIX_DEFAULT_PREFIX=
MATRIX_DEFAULT_PREFIX_REPLY=false
CHATGPT_CONTEXT=thread
MATRIX_THREADS=true
