### ISSUE TITLE
No mechanism to reset conversation context when using rooms instead of threads

### ISSUE THREAD

**Issue by c0mmando** [matrixgpt/matrix-chatgpt-bot#135]
Though I now prefer to use threads, I can't figure out a way to reset the bot's previous conversation context associated with the room. It would be an improvement to have an option that treats every room query as a new conversation for public rooms.

In my public room with no threads, users have run various jailbreaks against the chatgpt bot and now some of these jailbreaks cannot be reversed which degrades user experience. An enhancement would be to allow conversation context to be reset with each new query or provide a backend mechanism to reset context manually.

**Comment by Dual-0** [comment]
I think threads is the way to go. OpenAI use threads in there ChatGPT web application too. Maybe you can cleanup your conversations in your keyv storage backend, to dirty fix it.

**Comment by gruenfink** [comment]
Some additional chat bot commands could solve this quite handily:

- !chat PROMPT (request with !chat context)
- !ask PROMPT (request without context)
- !reset (reset current room context)

API calls are getting quite expensive with full context, and many prompts don't need context at all.

**Comment by c0mmando** [comment]
I reset the bot and implemented threads. Threads are certainly the way to go.
