### ISSUE TITLE
Decryption error: 'missing field `algorithm` at line 1 column 74'

### ISSUE THREAD

**Issue by PaarthShah** [matrixgpt/matrix-chatgpt-bot#138]
Running via `docker-compose` on ubuntu 20.04. The room in question is a 2 person 1 bot group chat between my homeserver (running latest synapse, and where the bot's account is hosted) and matrix.org.

```
Thu, 16 Mar 2023 03:22:17 GMT [ERROR] [MatrixClientLite] Decryption error on !HLtUHTYVtqVKvFGpYD:redacted.com $oS-5xha9-wdrsR3eVbFnCd6UKoeMt1wWTw4DCevt1fg [Error: missing field `algorithm` at line 1 column 74] {
  code: 'GenericFailure'
}
Thu, 16 Mar 2023 03:22:17 GMT [ERROR] [index] Failed decryption event!
[object Object]
Thu, 16 Mar 2023 03:22:17 GMT [ERROR] [MatrixClientLite] Decryption error on !HLtUHTYVtqVKvFGpYD:redacted.com $BzbSKuQDJ8jZg7vxlrUzW_lWoc03UZrdG5zdH3-HG6E [Error: missing field `algorithm` at line 1 column 74] {
  code: 'GenericFailure'
}
Thu, 16 Mar 2023 03:22:17 GMT [ERROR] [index] Failed decryption event!
[object Object]
Thu, 16 Mar 2023 03:22:17 GMT [ERROR] [MatrixClientLite] Decryption error on !HLtUHTYVtqVKvFGpYD:redacted.com $RI-9lrlg0XFfv_7a4W0GhO3X2BmjwwTOyLAOV9jqG4s [Error: missing field `algorithm` at line 1 column 74] {
  code: 'GenericFailure'
}
Thu, 16 Mar 2023 03:22:17 GMT [ERROR] [index] Failed decryption event!
[object Object]
```

**Comment by jame25** [comment]
I get the same error (in my case: Error: missing field 'algorithm' at line 1 column 13), running via `docker-compose` on Debian 11. Bot functions as expected, however this error periodically occurs (sometimes hours apart) and results in the following message being posted in the room: "I couldn't decrypt the message :( Please add me to an unencrypted room."

**Comment by PaarthShah** [comment]
For what it's worth, this may be very stale now, and I haven't had any issues in the last couple of months.
