### ISSUE TITLE
GPT-4 support

### ISSUE THREAD

**Issue by sibbl** [matrixgpt/matrix-chatgpt-bot#142]
I'd appreciate it, if the chatgpt-api module could be updated to the latest 1.31 version (which includes support for GPT-4 model) and a new docker container could be released.

**Comment by sibbl** [comment]
I've opened the following PR: https://github.com/matrixgpt/matrix-chatgpt-bot/pull/145

Meanwhile `npm update` can be used. However, this has to be called every time the container is recreated, e.g. by changing some detail in the docker compose configuration.

**Comment by bertybuttface** [comment]
Closed by https://github.com/matrixgpt/matrix-chatgpt-bot/pull/154
