### ISSUE TITLE
Optionally return errors in chat

### ISSUE THREAD

**Issue by mrled** [matrixgpt/matrix-chatgpt-bot#148]
As a feature request, would you consider having the bot respond with any error messages it receives? It would be useful if I could see the problem in my Matrix client, rather than having to follow the bot logs to get it. 

One way this would be useful: if I'm on my phone, I can log in to OpenAI and increase my billing quota, but I would probably wait to ssh to the server running the bot and follow the logs until I'm at a real computer. If the bot tells me that I am having a quota problem, I can fix it for my users while I'm still remote.

**Comment by max298** [comment]
We've already discussed this earlier in #55 and #91, however I do understand your point.

Maybe we want to introduce a setting like `SHOW_ERROR_DETAILS` to the env?

**Comment by mrled** [comment]
Yeah, I'd be interested in something like that.

I see in those other threads that there is concern that sensitive data could be leaked. I'm not sure if all of the errors from the OpenAI API look like this or not, but for the error I was seeing related to the billing quota, there was a verbose message and a shorter error code. Even just the shorter code would be pretty useful to me, if there is concern in sharing the whole message.

**Comment by max298** [comment]
I feel like the short error code would be something we could show by default. Just add the error-code to the message, like "The bot has encountered an error, please contact your administrator (Error code XX)."

**Comment by bertybuttface** [comment]
Closed by https://github.com/matrixgpt/matrix-chatgpt-bot/pull/155
