### ISSUE TITLE
I see big applications for this.

### ISSUE THREAD

**Issue by MetricZero** [matrixgpt/matrix-chatgpt-bot#151]
Just like with Midjourney's bot, but apply it to your own personal AI agent that can delineate tasks like BabyAGI or the new Microsoft's JARVIS will be able to do. You would be able to have basically an entire command center run by AI agents performing different tasks, even passing those tasks off to different agents that specialize in certain things.

I can see a system where we can create a natural language model chatbot, that can take commands and expand its abilities based on available models. We've got self reflection coming too.

I want to get involved and help develop this, but I don't know where to start. All I have is time.

**Comment by daedric7** [comment]
> Midjourney's bot

Can you clarify ?

**Comment by MetricZero** [comment]
With Midjourney, there's a whole bunch of commands and applications we can use it for on discord. Two main functions are describe and imagine (image-to-text and text-to-image). But with the advent of AI LLMs and the ability to access plugins right around the corner, I don't see it being too long before its possible to have an AI virtual assistant in Element.

**Comment by bertybuttface** [comment]
This is cool and I'm happy you are so excited but I'm closing this as too broad for now in favour of the discussion section. Feel free to post some ideas in the ideas section if you get some time.
