### ISSUE TITLE
Using a new API Key

### ISSUE THREAD

**Issue by ralfi** [matrixgpt/matrix-chatgpt-bot#156]
Hi, 

my first chatgpt API key is invalid after 1.4.23. Until this date everything works like a charm. Now i create a new Key without deleting the old key but the docker image breaks with a error if i use the new key.

How does changing key works?

**Comment by max298** [comment]
I don't see why setting a new API key in the environment file and restarting the container shouldn't work, we do not persist the key inside our storage backend.

Can you provide some more details, maybe the error log (of course with the redacted API key 😉 ) you're getting?

**Comment by ralfi** [comment]
Will give you more details asap... Thanks in advance

**Comment by ralfi** [comment]
Thinking about my first post i forget to tell you my "free" key valid time is expired. I think that's it. Using the web interface works further but i think openai have a key signature that checks all user config settings
