### ISSUE TITLE
Losing new room encryption after restart

### ISSUE THREAD

**Issue by deetungsten** [matrixgpt/matrix-chatgpt-bot#163]
Is it normal for the room encryption to break after you restart or repull the image? My existing rooms work but and new rooms fail with the error that it cannot decrypt the room.

Thank you!

**Comment by max298** [comment]
Hmh this should not happen at all, could you provide a way to reproduce? I don't know that much about the matrix apis and the way encryption works, maybe someone else can assist here?

**Comment by bertybuttface** [comment]
This will be because you aren't storing between runs of the tool. Make sure you setup volumes properly.
