### ISSUE TITLE
Request: Customized API-Servers

### ISSUE THREAD

**Issue by d13g4** [matrixgpt/matrix-chatgpt-bot#172]
Hi!
I am running my own llama-based chat-ai on my pc (fastchat with vicuna in my case) which provides a open-ai compatible api.
I would like to have the option to change the api-url to my own; I am sure it could be a really nice feature.
Sorry for posting it as an issue, I didn't know where else - I hope you would consider it anyway.

**Comment by max298** [comment]
You can already do this since https://github.com/matrixgpt/matrix-chatgpt-bot/pull/161
Just use a api for llama which is compatible to the openai api like [this one](https://github.com/go-skynet/LocalAI) and set the reverse proxy (`CHATGPT_REVERSE_PROXY`) environment of the bot

**Comment by d13g4** [comment]
hm. maybe i configured it wrong, but that didn't work. i get a 401 with the bot but have no problems with the api when using curl. i will, if wanted/needed/interested investigate further and attach more information. maybe its a misconfiguration, maybe a bug? in any case: i tried exactly that a couple of hours before posting the message above...
