### ISSUE TITLE
MATRIX_WHITELIST_ROOMS

### ISSUE THREAD

**Issue by Sampozzo** [matrixgpt/matrix-chatgpt-bot#173]
Hello, i'm trying to have the bot running only inside some rooms with MATRIX_WHITELIST_ROOMS=room:myserver.com but it doesn't seems to work, the bot reply to all users. If i specify users with MATRIX_WHITELIST it works. 

What i'm missing?

Thank you very much.

**Comment by bertybuttface** [comment]
`MATRIX_WHITELIST_ROOMS` is not implemented currently, that isn't made clear but should be.

**Comment by bertybuttface** [comment]
The docs were incorrect:

`MATRIX_WHITELIST_ROOMS` should be `MATRIX_ROOM_WHITELIST`
