### ISSUE TITLE
On too long reply, the bot gets stuck

### ISSUE THREAD

**Issue by VeRychard** [matrixgpt/matrix-chatgpt-bot#202]
When I get a longer response from the bot, the answer gets trimmed. 
So far so good, however on the openAI's chat web UI there is a button to continue the response, so it can finish the whole answer.

It would be awesome to have this feature, because this way I have to copy my whole question again and open up the web browser to get the full answer.

Cheers

**Comment by VeRychard** [comment]
nvm, I realized that with the "continue" reply it finishes the previous one. 😎

**Comment by bertybuttface** [comment]
Can you update the README to point this out to others and put in a PR please

**Comment by VeRychard** [comment]
sure thing! sent it

**Comment by bertybuttface** [comment]
Thanks for doing that, should help everyone out 👍
