### ISSUE TITLE
Insufficent_quota

### ISSUE THREAD

**Issue by chitrangad** [matrixgpt/matrix-chatgpt-bot#217]
I installed the bot via docker compose and setup my env file as per example.
The bot starts successfully and I can open the chat. However, I'm getting the insufficient_quota error.
I checked my OpenAI account and I have zero calls so far. I'm using free account. Using 3.5-turbo

"error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }

**Comment by tcpipuk** [comment]
That error is coming from OpenAI, so that looks very much like an OpenAI issue?

**Comment by chitrangad** [comment]
Yes, looks like it. A quick search tells me I'm not the only one facing it. It's an issue with OpenAI API after they went live with monetization model. 
I will close the issue as it's not related to the project.
