### ISSUE TITLE
error: "Can't join remote room because no servers that are in the room have been provided."

### ISSUE THREAD

**Issue by nige-n15** [matrixgpt/matrix-chatgpt-bot#226]
I am encountering the below issue on my server that is set-up using an  ansible playbook.

Oct 10 21:52:10 localhost matrix-bot-chatgpt[481587]:   statusCode: 404,
Oct 10 21:52:10 localhost matrix-bot-chatgpt[481587]:   errcode: 'M_UNKNOWN',
Oct 10 21:52:10 localhost matrix-bot-chatgpt[481587]:   error: "Can't join remote room because no servers that are in the room have been provided.",
Oct 10 21:52:10 localhost matrix-bot-chatgpt[481587]:   retryAfterMs: undefined
Oct 10 21:52:10 localhost matrix-bot-chatgpt[481587]: }
Oct 10 21:52:10 localhost matrix-bot-chatgpt[481587]: Node.js v19.9.0
Oct 10 21:52:11 localhost matrix-bot-chatgpt[481587]: error Command failed with exit code 1.
Oct 10 21:52:11 localhost matrix-bot-chatgpt[481587]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Oct 10 21:52:11 localhost systemd[1]: matrix-bot-chatgpt.service: Main process exited, code=exited, status=1/FAILURE

I checked the common issues.

Here. are the relevant lines from my playbook config .yml.

# This is the default username
# matrix_bot_chatgpt_matrix_bot_username_localpart: 'bot.chatgpt'
matrix_bot_chatgpt_enabled: true

# Obtain a new API key from https://platform.openai.com/account/api-keys
matrix_bot_chatgpt_openai_api_key:***myvalidapikey***

# This is the default username
# matrix_bot_chatgpt_matrix_bot_username_localpart: 'bot.chatgpt'

# Configuring the system promt used, needed if the bot is used for special tasks.
# More information: https://github.com/mustvlad/ChatGPT-System-Prompts
matrix_bot_chatgpt_matrix_bot_prompt_prefix: 'Instructions:\nYou are ChatGPT, a large language model trained by OpenAI.'
matrix_bot_chatgpt_matrix_access_token: access_token

I've followed the instructions here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bot-chatgpt.md 

Any ideas appreciated

**Comment by nige-n15** [comment]
This is the complete log from when it tries to start:

Oct 10 21:53:18 localhost matrix-bot-chatgpt[482475]: yarn run v1.22.19
Oct 10 21:53:18 localhost matrix-bot-chatgpt[482475]: $ node --enable-source-maps dist/index.js
Oct 10 21:53:19 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:19 GMT [INFO] [index] Starting bot using ChatGPT model: gpt-3.5-turbo
Oct 10 21:53:19 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:19 GMT [INFO] [index] Using promptPrefix: <|im_sep|>Instructions:\nYou are ChatGPT, a large language model trained by OpenAI.
Oct 10 21:53:19 localhost matrix-bot-chatgpt[482475]: Current date: October 10, 2023<|im_sep|>
Oct 10 21:53:20 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:20 GMT [ERROR] [MatrixHttpClient] (REQ-5) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Oct 10 21:53:20 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:20 GMT [ERROR] [MatrixHttpClient] (REQ-6) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Oct 10 21:53:20 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:20 GMT [ERROR] [MatrixHttpClient] (REQ-7) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Oct 10 21:53:20 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:20 GMT [INFO] [MatrixClientLite] End-to-end encryption enabled
Oct 10 21:53:20 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:20 GMT [INFO] [index] Bot started!
Oct 10 21:53:22 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:22 GMT [ERROR] [MatrixHttpClient] (REQ-12) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Oct 10 21:53:22 localhost matrix-bot-chatgpt[482475]: Tue, 10 Oct 2023 20:53:22 GMT [ERROR] [MatrixHttpClient] (REQ-11) {
Oct 10 21:53:22 localhost matrix-bot-chatgpt[482475]:   errcode: 'M_UNKNOWN',
Oct 10 21:53:22 localhost matrix-bot-chatgpt[482475]:   error: "Can't join remote room because no servers that are in the room have been provided."

**Comment by bertybuttface** [comment]
Cannot reproduce.
