### ISSUE TITLE
max tokens is always 3071

### ISSUE THREAD

**Issue by Dual-0** [matrixgpt/matrix-chatgpt-bot#246]
Hello,

no matter which model I use e.g. `gpt-4-32k-0613` or the new `gpt-4-1106-preview` with 128k context window I always get:
```
Mon, 06 Nov 2023 21:44:24 GMT [ERROR] [OpenAI-API Error: Error: Prompt is too long. Max token count is 3071, but prompt is 3539 tokens long.]
TypeError: Cannot read properties of undefined (reading 'response')
     at CommandHandler.onMessage (file:///opt/matrix_gpt_bot/3.1.4/dist/handlers.js:132:86)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

thanks in advance

**Comment by jame25** [comment]
**gpt-4-1106-preview** is working perfectly for me with v3.1.4, I did however also [update npm](https://github.com/matrixgpt/matrix-chatgpt-bot/issues/120#issuecomment-1451815620) to latest version.

**Comment by Dual-0** [comment]
I think we need the options `maxContextTokens` and `maxPromptTokens` from [use-client.js](https://github.com/waylaidwanderer/node-chatgpt-api/blob/a424398bd19761553b6587f64565881e06cbdb00/demos/use-client.js#L23C1-L27C30) in [clientOptions](https://github.com/matrixgpt/matrix-chatgpt-bot/blob/64fc3f2488013f2c6dc750804bfbe9cd810db64c/src/index.ts#L60C1-L69C5)
My test went well with:
```
    maxContextTokens: 128000,
    maxPromptTokens: 32000,
```


> **gpt-4-1106-preview** is working perfectly for me with v3.1.4, I did however also [update npm](https://github.com/matrixgpt/matrix-chatgpt-bot/issues/120#issuecomment-1451815620) to latest version.

you have made an input with over 3071 tokens?

**Comment by Dual-0** [comment]
Thanks @max298 

I raised `maxContextTokens: 128000`. I don't use `maxPromptTokens` at the moment. Works good so far. Do we need `maxPromptTokens`?
