### ISSUE TITLE
 HTTP 503 - {"error":{"code":503,"message":"Service Unavailable.","param":null,"type":"cf_service_unavailable"}}]

### ISSUE THREAD

**Issue by adelorenzo** [matrixgpt/matrix-chatgpt-bot#249]
Hello,

I've been using the bot without any issues until today. I got the error message below:

 `HTTP 503 - {"error":{"code":503,"message":"Service Unavailable.","param":null,"type":"cf_service_unavailable"}}]`

Can someone please help with this? Thank you very much.

**Comment by bertybuttface** [comment]
OpenAI are having scaling issues, you can see the notice at the top of the page when you use ChatGPT itself.
