### ISSUE TITLE
Support streaming responss

### ISSUE THREAD

**Issue by MuhammadHadiofficial** [matrixgpt/matrix-chatgpt-bot#252]
Any way to enable streaming response to consume server sent events and show the word by word generation on chat?

**Comment by tcpipuk** [comment]
I had no idea the OpenAI API returns SSE for streaming responses!

In either case, it'd be incredibly spammy for most servers if the bot posts that many message edits, especially for longer messages... I'd be worried about that being an option, even if it's disabled by default.

**Comment by bertybuttface** [comment]
Yeah agreed I don't think we have a good solution for this from the Matrix end of things.
