### ISSUE TITLE
Don't crash the app, throw errors to the chat

### ISSUE THREAD

**Issue by TriplEight** [matrixgpt/matrix-chatgpt-bot#55]
It would be better if the chat bot would answer with auth errors and `checkForChatGPTAtCapacity` messages rather than crushing the app and making to have it restarted.
Or as an alternative, output them into the log and re-attempting it over and over.

**Comment by bertybuttface** [comment]
Closed by https://github.com/matrixgpt/matrix-chatgpt-bot/pull/91
