### ISSUE TITLE
Can the bot be logged into my Matrix account at the same time I am so it can reply to my messages?

### ISSUE THREAD

**Issue by chagai95** [matrixgpt/matrix-chatgpt-bot#64]

**Comment by bertybuttface** [comment]
Yes

**Comment by chagai95** [comment]
I think I didn't express myself well enough, I meant have it answer _as if it's me answering_ so I don't have to answer my chats...

**Comment by bertybuttface** [comment]
Don't quote me on this as I've never tried but I think you could give an access token for your user to the bot instead of creating its own user. Try it and report back?

**Comment by bertybuttface** [comment]
You would need to set MATRIX_PREFIX to false if you wanted to reply to any message without a prefix.

**Comment by chagai95** [comment]
Pretty cool, I'll try it soon enough, is there a way to activate/deactivate in a specific room and also a way to inject some messages before a chat starts? In order to tell chat gpt I would like them to answer like a human answering a chat... Or maybe even to inject some context via older messages?

**Comment by bertybuttface** [comment]
Neither of those features have been implemented yet but PRs are welcome.

**Comment by max298** [comment]
I'd love to help, but I don't quite understand what we are trying to accomplish here.

Would you like to customize the the existing `👋 Hello, I'm ChatGPT bot! Matrix E2EE: …`-message?

**Comment by chagai95** [comment]
I haven't yet tried the bot, so I'm not sure exactly what is needed but I'd like to be able to tell chatgpt to continue my conversation with my friends based on the previous messages in the chat and pretend to be me - so no message at all saying "I'm chat gpt"

**Comment by bertybuttface** [comment]
To close this we need:

1. Control over which rooms the bot does and does not respond in (see `room-acl`) branch.
2. Ability to turn welcome message off via a setting.

I think that is pretty much it.

**Comment by bertybuttface** [comment]
1 should be fixed on main branch already.

2 is fixed by https://github.com/matrixgpt/matrix-chatgpt-bot/pull/99

**Comment by chagai95** [comment]
Cool, thx! I'm excited to try it out!
