### ISSUE TITLE
Optionally disable replies to audio messages or prevent chatgpt from replying to this.

### ISSUE THREAD

**Issue by bramenn** [matrixgpt/matrix-chatgpt-bot#88]
I am making a plug-in to send audio to the room and have Whisper convert them to text.

The possibility of disabling audio message replies, as it interferes with text generation in Whisper. Thank you for considering my suggestion.

![image](https://user-images.githubusercontent.com/50601186/217155385-3c531d3c-9ceb-41f8-86d0-a75f330aa66c.png)

**Comment by max298** [comment]
I even think this should be the default behavior, as ChatGPT won't interpret anything other than text.

**Comment by max298** [comment]
I've just created #90.

However I'd like to discuss if we should add another environment parameter like `IGNORE_NON_TEXT_MSG` or just ignore non-text messages by default. I think from a user perspective it would be nice to have the possibility of getting a reply from ChatGPT saying it can't process non-text, so you know whats up instead of just silence. So another ENV would make sense in my opinion.

**Comment by bertybuttface** [comment]
> I've just created #90.
> 
> However I'd like to discuss if we should add another environment parameter like `IGNORE_NON_TEXT_MSG` or just ignore non-text messages by default. I think from a user perspective it would be nice to have the possibility of getting a reply from ChatGPT saying it can't process non-text, so you know whats up instead of just silence. So another ENV would make sense in my opinion.

I think we just ignore by default, ChatGPT will never add image support and if we choose to it will have to use a different AI backend and that isn't on the roadmap by now.

**Comment by max298** [comment]
True, but I like how users might upload some pictures / other stuff and ChatGPT answers that it is not able to process the attachment, letting the user know this won't work, instead of just silence.

**Comment by bramenn** [comment]
It should be default to ignore these types of unsupported messages. If we want it to say something we have several options:

- Continue to print the message that chatgpt gives us.
- Just react with a ❌ the unsupported messages.
- Reply with a preconfigured notice
- Print only a log that warns that this message is not supported.
